- name: First Ansible directive
  hosts: bulletins
  become: false
  tasks:
    - name: kill background mpv process
      shell: ps -ef | grep mpv | grep bin | awk '{print $2}' | xargs kill &>/dev/null
